name: Java CI with Maven

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-runner

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    #- name: Install dependencies
      #run: |
        #npm install

    #- name: Build the frontend
      #run: |
        #npm run build  # or your actual build command
        
    - name: Copy and chmod artifact
      run: |
        #ARTIFACT_PATH=/home/ubuntu/actions-runner/_work/node-hello/node-hello/
        #DEST_PATH=/application/frontend
        #cp "$ARTIFACT_PATH" "$DEST_PATH"
        sudo cp /home/ubuntu/actions-runner/_work/node-hello/node-hello/* /application/frontend
        sudo chmod 777 * /application/frontend
        echo "Copied artifact to $DEST_PATH"
        sudo systemctl restart apache2
