name: Java CI with Maven

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-runner

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    #- name: Install dependencies
      #run: |
        #npm install

    #- name: Build the frontend
      #run: |
        #npm run build  # or your actual build command
    - name: Copy frontend build to Apache directory
      run: |
        cd /application/
        sudo rm -rf frontend
        sudo cp -r /home/ubuntu/actions-runner/_work/node-hello/node-hello /application/
        sudo mv /application/node-hello /application/frontend
        sudo chmod -R 777 /application/frontend
        sudo systemctl restart apache2
